version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ~/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-pro
    ports:
      - 8081:8081